
# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: windows-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'connection1'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az config set extension.use_dynamic_install=yes_without_prompt
      az iot hub device-identity create --hub-name  myiothubdevops --device-id MyPythonDevice
      $env:CONNECTION_STRING = az iot hub device-identity connection-string show --hub-name myiothubdevops --device-id MyPythonDevice --output tsv
      $env:CONNECTION_STRING

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'SimulatedDevice.py'
    failOnStderr: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'connection1'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az iot hub device-identity delete --device-id MyPythonDevice --hub-name myiothubdevops'
